name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "0 9,16,21 * * 1,3,7" # See https://crontab.guru/#0 9,16,21 * * 1,3,7

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "mirfanfad@gmail.com"
          git config --local user.name "mirfanfad"
          git add -A
          
          git commit -m "🤖 : Push private code!"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force-with-lease: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
